"""Check render.yaml against the rules Render enforces at sync time.

Every other quality gate in this repository runs the code. None of them
reads the deployment blueprint, so a blueprint can be wrong in a way that
the full suite, ruff, mypy and bandit all pass — and the failure surfaces
only in Render's dashboard, as a sync that refuses to deploy anything.

That is not hypothetical. This file exists because it happened: the
blueprint declared RENDER_GIT_COMMIT and RENDER_SERVICE_NAME with a
`fromService` block pointing at the service being defined, and Render
answered

    services[0].envVars[2] cannot refer to reference env vars
    RENDER_GIT_COMMIT for service (web link-intel-web)

for both, failing the entire sync. Nothing was deployed. The variables
were never needed in the first place — Render injects its own RENDER_*
variables into every service, and app/config.py reads them from the
environment with a None fallback.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

BLUEPRINT = Path(__file__).resolve().parent.parent / "render.yaml"

# Reserved variables the platform sets by itself. Declaring one is at best
# redundant and, for a self-reference, fatal to the sync.
RENDER_PROVIDED_PREFIX = "RENDER_"


@pytest.fixture(scope="module")
def blueprint() -> dict:
    return yaml.safe_load(BLUEPRINT.read_text())


def _web_env(blueprint: dict) -> list[dict]:
    return blueprint["services"][0]["envVars"]


def test_no_service_refers_to_its_own_env_vars(blueprint: dict) -> None:
    """A `fromService` pointing at the service being defined fails the sync."""
    for service in blueprint["services"]:
        own_name = service["name"]
        for entry in service.get("envVars", []):
            source = entry.get("fromService")
            if source is None:
                continue
            assert source.get("name") != own_name, (
                f"{service['name']}.{entry['key']} reads an env var from itself via "
                "fromService. Render rejects this and the whole blueprint sync fails. "
                "If the value is a RENDER_* variable, delete the entry — the platform "
                "already provides it."
            )


def test_no_render_reserved_variable_is_declared(blueprint: dict) -> None:
    """RENDER_* variables come from the platform, not from the blueprint."""
    declared = [entry["key"] for entry in _web_env(blueprint) if entry["key"].startswith(RENDER_PROVIDED_PREFIX)]
    assert declared == [], (
        f"render.yaml declares platform-reserved variables: {declared}. Render sets "
        "these itself on every build; app/config.py reads them from the environment. "
        "Declaring one is redundant at best and, with fromService, breaks the sync."
    )


def test_the_secret_whose_absence_is_silent_is_still_prompted_for(blueprint: dict) -> None:
    """FIELD_ENCRYPTION_KEY must be sync:false, not absent and not generated.

    Absent, app/config.py falls back to a default published in this
    repository and nothing warns — TOTP secrets and webhook URLs get
    encrypted under a key anyone can read. Generated, Render would invent a
    value the collector and rotation script could never reproduce, since
    they read the same key from GitHub Actions secrets.
    """
    entry = next((e for e in _web_env(blueprint) if e["key"] == "FIELD_ENCRYPTION_KEY"), None)
    assert entry is not None, (
        "FIELD_ENCRYPTION_KEY is not in render.yaml, so a blueprint deploy never "
        "asks for it and the published default silently applies."
    )
    assert entry.get("sync") is False, "FIELD_ENCRYPTION_KEY must be sync:false"
    assert "generateValue" not in entry, (
        "FIELD_ENCRYPTION_KEY must not be generated by Render — it has to match the "
        "value held in GitHub Actions secrets."
    )


def test_the_blueprint_still_uses_no_docker(blueprint: dict) -> None:
    """A standing project constraint, checked rather than remembered."""
    for service in blueprint["services"]:
        assert service.get("runtime") == "python", (
            f"{service['name']} is not on the native Python runtime. This project "
            "deploys without Docker by explicit requirement."
        )
        assert "dockerfilePath" not in service and "dockerCommand" not in service


def test_every_service_and_database_stays_on_a_free_plan(blueprint: dict) -> None:
    """Zero infrastructure cost is unconditional here, so assert it."""
    for service in blueprint["services"]:
        assert service.get("plan") == "free", f"{service['name']} is not on the free plan"
    for database in blueprint.get("databases", []):
        assert database.get("plan") == "free", f"{database['name']} is not on the free plan"
